# four node (three workers) cluster config
kind: Cluster            # this file describes the Kubernetes infrastructure -- a "cluster" 
apiVersion: kind.x-k8s.io/v1alpha4
name: kind               # this is a default for Kubernetes-in-Docker (KinD), but be explicit
nodes:                   # the nodes are the host servers that implement your Kubernetes cluster
- role: control-plane    # one control plane node offers no redundancy for high availability
- role: worker           # each worker node can run your container workloads
- role: worker           # multiple workers is good practice and offers protection from node failures
- role: worker
