apiVersion: apps/v1       # remember to use apps/v1 instead of merely v1
kind: Deployment
metadata:
  labels:                 # labels allow you to tag your object with a set of key/value pairs
    app: demo
  name: demo              # it is customary to have an "app" key with a value to identify your object
spec:                     # the object specification begins here, note no indentation!
  replicas: 1             # for "spec.replicas", think ASG "Desired" size
  selector:               # you can enable the deployment to acquire/own pods which match your "selector"
    matchLabels:          # the most common selector clause is to match labels on existing Pods
      app: demo
  template:               # for "spec.template", think ASG "launch template" setting
    metadata:             #
      labels:             #
        app: demo         #
    spec:                 #
      containers:         #
      - name: demo        #
        image: demo:1.0.0 #
