apiVersion: apps/v1
kind: DaemonSet              # the object schema Kubernetes uses to validate this manifest
metadata:
  labels:
    app: demo-daemon
  name: demo-daemon
spec:
                             # huh ... no "replicas" attribute?
  selector:
    matchLabels:
      app: demo-daemon       # pods in this namespace and with this label are members
  template:
    metadata:
      labels:
        app: demo-daemon
    spec:
      containers:
      - name: demo
        image: demo:1.0.0    # re-using your demo container image, because you can ...
